{% set name = "av2" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/argoai/argoverse2-api/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bb88b8d4b2e6c4a3e0eeb43a4c7868eb64193da1d61863452f73b5e67a521fa1

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - maturin

  host:
    - maturin
    - pip
    - python
    - setuptools >=42
    - wheel

  run:
    - av
    - click
    - joblib
    - kornia
    - matplotlib-base
    - maturin
    - nox
    - numba
    - numpy >=1.21.5
    - openblas
    - opencv
    - openssl
    - pandas
    - pip
    - polars
    - pyarrow
    - pyproj
    - python
    - rich
    - rust
    - scipy
    - pytorch
    - tqdm
    - universal_pathlib

test:
  imports:
    - av2
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/argoai/av2-api
  summary: The official API of the Argoverse 2 dataset.
  description: |
    The official API of the Argoverse 2 dataset.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://github.com/argoai/av2-api
  dev_url: https://github.com/argoai/av2-api

extra:
  recipe-maintainers:
    - benjaminrwilson
